# MikroTik SSH Script Runner Configuration
# Set password_encrypted to false for plain text passwords (debug mode)
# Set password_encrypted to true for encrypted passwords (production mode)
password_encrypted: true
encryption_key: "MKT_Runner_SecretKey_2025_32chars"  # Used when password_encrypted is true

# Default MikroTik commands (can be overridden per router)
default_commands:
  list_scripts: ":foreach s in=[/system script find] do={ :put [/system script get $s name] }"
  get_comment: ":put [system/script/ get [find name=\"{script_name}\"] comment ]"

routers:
  - name: "Casa Daniel"
    host: "192.168.10.1"
    port: 22
    username: "adminssh"
    password: bRjlWNRm1NSFxOcJLho1Fg==
    user_level: 1

  - name: "Router TF" 
    host: "10.1.1.1"
    port: 22
    username: "admin"
    password: saUwovO3glSRS3akC0NAbg==
    user_level: 2

  - name: "Router borda"
    host: "192.168.0.254"
    port: 22
    username: "admin"
    password: saUwovO3glSRS3akC0NAbg==
    user_level: 1